URL:https://www.amazon.ca/

Username:sharan@gmail.com
Password:test

Email: sharan@gmail.com

Browser: Chrome

ProductName: Canon dslr

Fullname: Testing
PHnum: 9876878999
Address: Chennai
City: Chennai
PC: Chennai